### ISSUE TITLE
Warnings in logs of HA 

### ISSUE THREAD

**Issue by Knightcort** [davidrustingha/F1-Calendar-Card#5] opened 2021-11-28 13:21 UTC
**Describe the bug**
There are a lot of warnings published in HA log, title: "Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{% if (as_timestamp(strptime(state_attr('calendar.f1_sprint_race', 'start_time'), '%d %h %m'))......"

**To Reproduce**
See logs of HA.

**Expected behavior**
Hopefully you want to help to get rid of the warning message.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a I suppose

**Smartphone (please complete the following information):**
n/a I suppose

**Additional context**
the body of the warning is been copied below:

Logger: homeassistant.helpers.template
Source: helpers/template.py:1254
First occurred: 13:24:44 (850 occurrences)
Last logged: 14:12:00

Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{% if (as_timestamp(strptime(state_attr('calendar.f1_sprint_race', 'start_time'), '%d %h %m')) | timestamp_custom('%W')| float) == (now().isocalendar()[1]) %} on {% else %} off {% endif %}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'timestamp_custom' got invalid input 'None' when rendering template '{% if (as_timestamp(strptime(state_attr('calendar.f1_sprint_race', 'start_time'), '%d %h %m')) | timestamp_custom('%W')| float) == (now().isocalendar()[1]) %} on {% else %} off {% endif %}' but no default was specified. Currently 'timestamp_custom' will return 'None', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'float' got invalid input 'None' when rendering template '{% if (as_timestamp(strptime(state_attr('calendar.f1_sprint_race', 'start_time'), '%d %h %m')) | timestamp_custom('%W')| float) == (now().isocalendar()[1]) %} on {% else %} off {% endif %}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'strptime' got invalid input '2021-12-04 17:00:00' when rendering template '{% if state_attr('calendar.f1_qualification', 'start_time') == None or as_timestamp(strptime(state_attr('calendar.f1_qualification', 'start_time'), '%d %h %m')) | timestamp_custom('%W')| float != (now().isocalendar()[1]) %} No qualification this week {% else %} {{ as_timestamp(strptime(state_attr('calendar.f1_qualification', 'start_time'), '%d %h %m')) | timestamp_custom('%H:%M') }} {% endif %}' but no default was specified. Currently 'strptime' will return '2021-12-04 17:00:00', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'strptime' got invalid input '2021-12-03 17:00:00' when rendering template '{% if state_attr('calendar.f1_fp2', 'start_time') == None or as_timestamp(strptime(state_attr('calendar.f1_fp2', 'start_time'), '%d %h %m')) | timestamp_custom('%W')| float != (now().isocalendar()[1]) %} No 2nd free practice this week {% else %} {{ as_timestamp(strptime(state_attr('calendar.f1_fp2', 'start_time'), '%d %h %m')) | timestamp_custom('%H:%M') }} {% endif %}' but no default was specified. Currently 'strptime' will return '2021-12-03 17:00:00', however this template will fail to render in Home Assistant core 2022.1

**Comment by iron-LAN** [comment] 2021-12-07 08:14
Sorry for not getting to you earlier. Got lost in a dozen emails.

I am going to check this out. It seems that the template will render an error when the new version of HA will release, so I have to fix that for all users.

I'll get back to you asap!

**Comment by Knightcort** [comment] 2021-12-07 08:26
Hello,

No problem, we all are doing this in our spare time. And I’m not able to help you out or develop this myself. So patience helps ;).

John

**Comment by iron-LAN** [comment] 2021-12-08 08:38
@Knightcort It should be fixed now. Can you check and report back here? I haven't seen the issue myself, but it mightve gotten lost in my logfile.

**Comment by Knightcort** [comment] 2021-12-08 10:45
Hi,

Put the code in configuration.yaml and restarted it.

Issue seems still to be there. Please see the log:

Logger: homeassistant.helpers.template
Source: helpers/template.py:1254
First occurred: 11:41:00 (50 occurrences)
Last logged: 11:42:00

Template warning: 'timestamp_custom' got invalid input 'default' when rendering template '{% if as_timestamp(strptime(state_attr('calendar.f1_sprint_race', 'start_time'), '%d %h %m'), "default") | timestamp_custom('%W') == now().isocalendar()[1] %} on {% else %} off {% endif %}' but no default was specified. Currently 'timestamp_custom' will return 'default', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'strptime' got invalid input '2021-12-12 14:00:00' when rendering template '{% if state_attr('calendar.f1_race', 'start_time') == None or as_timestamp(strptime(state_attr('calendar.f1_race', 'start_time'), '%d %h %m'), "default") | timestamp_custom('%W')| float != (now().isocalendar()[1]) %} No race this week {% elif 'sprint' in state_attr('calendar.f1_race', 'message') %} No race this week {% else %} {{ as_timestamp(strptime(state_attr('calendar.f1_race', 'start_time'), '%d %h %m'), "default") | timestamp_custom('%H:%M') }} {% endif %}' but no default was specified. Currently 'strptime' will return '2021-12-12 14:00:00', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'strptime' got invalid input '2021-12-11 11:00:00' when rendering template '{% if state_attr('calendar.f1_fp3', 'start_time') == None or as_timestamp(strptime(state_attr('calendar.f1_fp3', 'start_time'), '%d %h %m'), "default") | timestamp_custom('%W')| float != (now().isocalendar()[1]) %} No 3rd free practice this week {% else %} {{ as_timestamp(strptime(state_attr('calendar.f1_fp3', 'start_time'), '%d %h %m'), "default") | timestamp_custom('%H:%M') }} {% endif %}' but no default was specified. Currently 'strptime' will return '2021-12-11 11:00:00', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'strptime' got invalid input '2021-12-12 14:00:00' when rendering template '{% if state_attr('calendar.f1_race', 'location') == None or as_timestamp(strptime(state_attr('calendar.f1_race', 'start_time'), '%d %h %m'), "default") | timestamp_custom('%W')| float != (now().isocalendar()[1]) %} No race track this week {% else %} {{ state_attr('calendar.f1_race', 'location') }} {% endif %}' but no default was specified. Currently 'strptime' will return '2021-12-12 14:00:00', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'strptime' got invalid input '2021-12-10 14:00:00' when rendering template '{% if state_attr('calendar.f1_fp2', 'start_time') == None or as_timestamp(strptime(state_attr('calendar.f1_fp2', 'start_time'), '%d %h %m'), "default") | timestamp_custom('%W')| float != (now().isocalendar()[1]) %} No 2nd free practice this week {% else %} {{ as_timestamp(strptime(state_attr('calendar.f1_fp2', 'start_time'), '%d %h %m'), "default") | timestamp_custom('%A %d %B') | replace("Monday", "maandag") | replace("Tuesday", "dinsdag") | replace("Wednesday", "woensdag") | replace("Thursday", "donderdag") | replace("Friday", "vrijdag") | replace("Saturday", "zaterdag") | replace("Sunday", "zondag") | replace("January", "januari") | replace("February", "februari") | replace("March", "maart") | replace("April", "april") | replace("May", "mei") | replace("June", "juni") | replace("July", "juli") | replace("August", "augustus") | replace("September", "september") | replace("October", "oktober") | replace("November", "november") | replace("December", "december") }} {% endif %}' but no default was specified. Currently 'strptime' will return '2021-12-10 14:00:00', however this template will fail to render in Home Assistant core 2022.1

**Comment by iron-LAN** [comment] 2021-12-08 12:00
@Knightcort I have pushed a new update. Could you check that? And if you still see the errors could you post them in code format? Makes it a little easier to look at haha

**Comment by Knightcort** [comment] 2021-12-08 12:30
Hi, still same error and additional the fact that "custom:atomic-calendar-revive" doesn't load anymore. How can I post errors in code format (at this moment I click on the error and make a copy of the window that appears, I'm stille learning in HA and GIT...).

**Comment by iron-LAN** [comment] 2021-12-08 12:43
Either command (if you're on Mac) or control + e, then paste the error log inside.

Maybe a stupid question but you do reload template entities after copy pasting the edited code?

EDIT:
Should look like this 
`This is some test code`

**Comment by iron-LAN** [comment] 2021-12-08 13:09
I've found another problem in the sprint sensor, so that should be fixed.

Im curious to see which errors you still have. The strptime errors should be gone because I cut that function out of the sensors completely. All of the default values are set so the template shouldnt throw errors anymore. I still havent seen them in my own log..

Keep me posted!

**Comment by Knightcort** [comment] 2021-12-08 13:12
Hi, I understand the code insert, thnks. 
As mentiond I restart the server in HA, I'm in the understanding that everything is then reloaded. 

See attached screenshot for what I'm doing after renewal of the code:
![image](https://user-images.githubusercontent.com/93401556/145211862-459af6a9-ae39-4bfd-b0d4-bf997996c6fd.png)

Hereby the logging after reaplying code:

```
Logger: homeassistant.helpers.template
Source: helpers/template.py:1254
First occurred: 13:23:00 (200 occurrences)
Last logged: 14:00:00

Template warning: 'float' got invalid input 'default' when rendering template '{% if state_attr('calendar.f1_sprint_qualifying', 'start_time') == 'None' or as_timestamp(state_attr('calendar.f1_sprint_qualifying', 'start_time'), 'default') | timestamp_custom('%W', 'default', 'default')| float != (now().isocalendar()[1]) %} No sprint qualification this week {% else %} {{ as_timestamp(state_attr('calendar.f1_sprint_qualifying', 'start_time'), 'default') | timestamp_custom('%H:%M') }} {% endif %}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'float' got invalid input 'default' when rendering template '{% if state_attr('calendar.f1_sprint_race', 'start_time') == 'None' or as_timestamp(state_attr('calendar.f1_sprint_race', 'start_time'), 'default') | timestamp_custom('%W', 'default', 'default')| float != (now().isocalendar()[1]) %} No sprint race this week {% else %} {{ as_timestamp(state_attr('calendar.f1_sprint_race', 'start_time'), 'default') | timestamp_custom('%A %d %B', 'default') | replace("Monday", "maandag") | replace("Tuesday", "dinsdag") | replace("Wednesday", "woensdag") | replace("Thursday", "donderdag") | replace("Friday", "vrijdag") | replace("Saturday", "zaterdag") | replace("Sunday", "zondag") | replace("January", "januari") | replace("February", "februari") | replace("March", "maart") | replace("April", "april") | replace("May", "mei") | replace("June", "juni") | replace("July", "juli") | replace("August", "augustus") | replace("September", "september") | replace("October", "oktober") | replace("November", "november") | replace("December", "december") }} {% endif %}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'float' got invalid input 'default' when rendering template '{% if state_attr('calendar.f1_sprint_race', 'start_time') == 'None' or as_timestamp(state_attr('calendar.f1_sprint_race', 'start_time'), 'default') | timestamp_custom('%W', 'default', 'default')| float != (now().isocalendar()[1]) %} No sprint race this week {% else %} {{ as_timestamp(state_attr('calendar.f1_sprint_race', 'start_time'), 'default') | timestamp_custom('%H:%M') }} {% endif %}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'float' got invalid input 'default' when rendering template '{% if state_attr('calendar.f1_sprint_qualifying', 'start_time') == 'None' or as_timestamp(state_attr('calendar.f1_sprint_qualifying', 'start_time'), 'default') | timestamp_custom('%W', 'default', 'default')| float != (now().isocalendar()[1]) %} No sprint qualification this week {% else %} {{ as_timestamp(state_attr('calendar.f1_sprint_qualifying', 'start_time'), 'default') | timestamp_custom('%A %d %B', 'default') | replace("Monday", "maandag") | replace("Tuesday", "dinsdag") | replace("Wednesday", "woensdag") | replace("Thursday", "donderdag") | replace("Friday", "vrijdag") | replace("Saturday", "zaterdag") | replace("Sunday", "zondag") | replace("January", "januari") | replace("February", "februari") | replace("March", "maart") | replace("April", "april") | replace("May", "mei") | replace("June", "juni") | replace("July", "juli") | replace("August", "augustus") | replace("September", "september") | replace("October", "oktober") | replace("November", "november") | replace("December", "december") }} {% endif %}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'timestamp_custom' got invalid input 'default' when rendering template '{% if as_timestamp(state_attr('calendar.f1_sprint_race', 'start_time'), 'default') | timestamp_custom('%W', 'default') == now().isocalendar()[1] %} on {% else %} off {% endif %}' but no default was specified. Currently 'timestamp_custom' will return 'default', however this template will fail to render in Home Assistant core 2022.1

```

And also a error from loading the google calandar after the last code adjustments:

```
Logger: frontend.js.latest.202111090
Source: components/system_log/__init__.py:190
First occurred: 13:23:23 (3 occurrences)
Last logged: 13:47:38

http://xxxxxxx/lovelace-basisdashboard/0:0:0 Uncaught
```

**Comment by iron-LAN** [comment] 2021-12-08 13:30
Thank you, that made it a lot more clear where the errors are exactly. Ive pushed another update. Could you check that?

Sorry to put you through all this, I don't understand why i'm not seeing the error..

EDIT: The last error message doesnt seem to be caused by the card, just a frontend error.
EDIT 2: I've made the mistake of deleting a function in the sensor. Im putting that back within a couple of minutes.

**Comment by iron-LAN** [comment] 2021-12-08 13:56
Could you try the updated code?

**Comment by Knightcort** [comment] 2021-12-08 15:08
updated the code, I've got this one:

```
Logger: homeassistant.helpers.template
Source: helpers/template.py:1254
First occurred: 16:03:00 (16 occurrences)
Last logged: 16:06:00

Template warning: 'timestamp_custom' got invalid input '0' when rendering template '{% if state_attr('calendar.f1_sprint_qualifying', 'start_time') == 'None' or as_timestamp(state_attr('calendar.f1_sprint_qualifying', 'start_time'), '0') | timestamp_custom('%W', '0') | float(0) != (now().isocalendar()[1]) %} No sprint qualification this week {% else %} {{ as_timestamp(state_attr('calendar.f1_sprint_qualifying', 'start_time'), '0') | timestamp_custom('%A %d %B', '0') | replace("Monday", "maandag") | replace("Tuesday", "dinsdag") | replace("Wednesday", "woensdag") | replace("Thursday", "donderdag") | replace("Friday", "vrijdag") | replace("Saturday", "zaterdag") | replace("Sunday", "zondag") | replace("January", "januari") | replace("February", "februari") | replace("March", "maart") | replace("April", "april") | replace("May", "mei") | replace("June", "juni") | replace("July", "juli") | replace("August", "augustus") | replace("September", "september") | replace("October", "oktober") | replace("November", "november") | replace("December", "december") }} {% endif %}' but no default was specified. Currently 'timestamp_custom' will return '0', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'timestamp_custom' got invalid input '0' when rendering template '{% if state_attr('calendar.f1_sprint_race', 'start_time') == 'None' or as_timestamp(state_attr('calendar.f1_sprint_race', 'start_time'), '0') | timestamp_custom('%W', '0') | float(0) != (now().isocalendar()[1]) %} No sprint race this week {% else %} {{ as_timestamp(state_attr('calendar.f1_sprint_race', 'start_time'), '0') | timestamp_custom('%A %d %B', '0') | replace("Monday", "maandag") | replace("Tuesday", "dinsdag") | replace("Wednesday", "woensdag") | replace("Thursday", "donderdag") | replace("Friday", "vrijdag") | replace("Saturday", "zaterdag") | replace("Sunday", "zondag") | replace("January", "januari") | replace("February", "februari") | replace("March", "maart") | replace("April", "april") | replace("May", "mei") | replace("June", "juni") | replace("July", "juli") | replace("August", "augustus") | replace("September", "september") | replace("October", "oktober") | replace("November", "november") | replace("December", "december") }} {% endif %}' but no default was specified. Currently 'timestamp_custom' will return '0', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'timestamp_custom' got invalid input '0' when rendering template '{% if state_attr('calendar.f1_sprint_race', 'start_time') == 'None' or as_timestamp(state_attr('calendar.f1_sprint_race', 'start_time'), '0') | timestamp_custom('%W', '0') | float(0) != (now().isocalendar()[1]) %} No sprint race this week {% else %} {{ as_timestamp(state_attr('calendar.f1_sprint_race', 'start_time'), '0') | timestamp_custom('%H:%M', '0') }} {% endif %}' but no default was specified. Currently 'timestamp_custom' will return '0', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'timestamp_custom' got invalid input '0' when rendering template '{% if state_attr('calendar.f1_sprint_qualifying', 'start_time') == 'None' or as_timestamp(state_attr('calendar.f1_sprint_qualifying', 'start_time'), '0') | timestamp_custom('%W', '0') | float(0) != (now().isocalendar()[1]) %} No sprint qualification this week {% else %} {{ as_timestamp(state_attr('calendar.f1_sprint_qualifying', 'start_time'), '0') | timestamp_custom('%H:%M', '0') }} {% endif %}' but no default was specified. Currently 'timestamp_custom' will return '0', however this template will fail to render in Home Assistant core 2022.1
```

**Comment by iron-LAN** [comment] 2021-12-08 16:38
Okay, im going to mark this issue as closed because I don't have the error myself and its pretty hard to trouble shoot it this way. The card should still work, but as soon as version 2022.1 is available it wont render. At that point I should get the errors too and itll be easier to fix.

**Closed as completed by iron-LAN** 2021-12-08 16:38 UTC
Labels: bug

**Comment by Knightcort** [comment] 2021-12-08 16:58
No problem, thanks for you’re help!
